PR for #44: Benchmarking
diegogentilepassaro/min_wage_rent pull request #45
Opened 2020-09-17 19:50 UTC by santiagohermo

I think we are in a good place to wrap #44 up. We can play a bit with the parameters as we go along. I think gabri already went through the notes, so I assigned you @diegogentilepassaro. It should be a really quick review.

I stored the `benchmark.pdf` note in `analysis\notes`. If you have a better idea about how to store it, I'm all ears.

Let me know if you have any comments/questions!

2020-09-29 13:49 UTC, diegogentilepassaro requested changes
One big comment: all the benchmarking exercise, including the notes, should live on its own analysis directory- i.e. /analysis/benchmarking-. 
Then, the preclean of the first difference will remain simple and easy, and the benchmarking preclean one can have the needed variables that we added here.

2020-09-29 13:49 UTC, diegogentilepassaro commented on analysis/notes/benchmark.Rmarkdown
> +- $\underline{\beta} = 0.1$, so housing demand is inelastic to income
Housing demand of the MW HH.

2020-09-29 13:49 UTC, diegogentilepassaro commented on analysis/notes/benchmark.Rmarkdown
> +- $\underline{\gamma} = - 0.7$ and $\overline{\gamma} = - 0.5$, so MW HH are more sensible to
This makes sense, but where are these numbers coming from? I am sympathetic towards the intuition that MW HH should be more sensible to rents, that is easy to defend. But do we at least have a sense of what is the elasticity of housing demand to rents that other papers estimate for the overall population or for some low or high income groups? 
A more complicated alternative, would be to assume that all households consume 1 unit of housing and what they also chose is the quality. Then things would be a function of the elasticities of housing quality to prices for each group and presumably we can get those from Van Dijk.

2020-09-29 13:49 UTC, diegogentilepassaro commented on analysis/notes/benchmark.Rmarkdown
> +- $k = 0.1$, similar to estimate of Diamond (2016, Table 5)
Very nice that we take that parameter from Diamond (2016).

2020-09-29 20:57 UTC, gabrieleborg commented on analysis/notes/benchmark.Rmarkdown
> +- $\underline{\gamma} = - 0.7$ and $\overline{\gamma} = - 0.5$, so MW HH are more sensible to
the gamma parameters, as well as the income elasticity beta, could be recovered from Albouy et al (2016). I saved it in `bibliography/housing_market/`. Here they show that indeed the price elasticity is approximately 2/3 in magnitude, so -.5 and -.7 for the 2 groups seem reasonable. As I previously anticipated to you though, they also estimate the income elasticity to be around .5, while we use a way more inelastic one (.1). You can find their results in tables 1, 2,3, and 4.

2020-09-29 21:02 UTC, santiagohermo reviewed
Thanks @gabrieleborg for implementing the benchmark plots! Overall the code makes sense to me. I made a few comments to simplify it a bit

2020-09-29 21:02 UTC, santiagohermo commented on analysis/first_differences/code/benchmark_test.do
> +	}
Given that we are not using `alpha` anymore, it looks like we don't need two functions. Right?

2020-09-29 21:04 UTC, santiagohermo commented on analysis/notes/benchmark.Rmarkdown
> +- $\underline{\beta} = 0.1$, so housing demand is inelastic to income
Implemented!

2020-09-30 13:42 UTC, gabrieleborg commented on analysis/first_differences/code/benchmark_test.do
> +	local mww_share_rentm = r(mean)
Yes, agree. But we still need the second block, to compute the average share of MW workers in the estimation sample!

2020-09-30 13:46 UTC, gabrieleborg commented on analysis/first_differences/code/benchmark_test.do
> +	}
That's slightly different, as the 2 functions compute the benchmark using two difference assumption on how to identify MW workers (that are needed in the benchmark as they enter as share). The first one assumes that all MW households are 2-workers households, while the second assumes that 1- and 2-workers households are uniformly distributed across income bins for renters ,and so the share of MW households identified through the census accounts for that.

2020-09-30 13:49 UTC, gabrieleborg commented
@diegogentilepassaro @santiagohermo I have implemented the requested changes. Let me know how it looks now.

2020-09-30 16:40 UTC, diegogentilepassaro commented
@gabrieleborg you are good to go on my end! Let's wait for @santiagohermo :D

2020-09-30 17:56 UTC, santiagohermo commented
Things look good on my end too, thanks @gabrieleborg!

2020-09-30 18:30 UTC, merged