PR for  #43 - dynamic panel data specs
diegogentilepassaro/min_wage_rent pull request #48
Opened 2020-09-27 23:36 UTC by gabrieleborg

As per our last conversation, I am sending #43 to PR. 

I additionally tried to build some MW change-date specific FE with the idea to compare MW changes occurring at different places at the same time, but this resulted to be less intuitive than I expected and so I paused that for the moment. I will keep thinking about that while you review this, so let me know if you come up with other possible ways to reduce the "large SE issue" (@diegogentilepassaro I remember we discussed something along the lines of what I tried for example).
Comments on the inclusion of entry cohort X period Fes can be found in [my post](https://github.com/diegogentilepassaro/min_wage_rent/issues/43#issuecomment-698963437) in #43.  
 

2020-09-29 20:58 UTC, diegogentilepassaro commented
@gabrieleborg before I review this please see comment [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/43#issuecomment-700065101). Knowing those figures will help us understand the pros of using an unbalanced panel better!

2020-09-29 21:02 UTC, gabrieleborg commented
@diegogentilepassaro working on it!

2020-09-29 21:24 UTC, gabrieleborg commented
@diegogentilepassaro here are the numbers:

**Old (balanced) panel:**

- States: 41
- zipcodes: 1143
- ever treated zipcodes: 712
- untreated zipcodes: 431

**New (unbalanced panel:**

- States: 49
- zipcodes: 3316
- ever treated zipcodes: 2080
- untreated zipcodes: 1236

2020-09-30 14:39 UTC, diegogentilepassaro commented
Thanks @gabrieleborg! Those numbers are really surprising and it seems super weird that we don't get down our SEs as we increase the number of clusters by 20% and the number of zipcodes per state by a factor of more than 2. I will take a careful look at the code and make some experiments while reviewing. 

The main alternative idea of specification that i will explore: Given that we have many zipcodes per state, instead of including zipcode FEs we could try exploiting variation within state and across zipcodes by including state FEs. In that case we will need to control for baseline zipocode characteristics to make sure that we take into account that some zipcodes are richer, etc, and we need to allow for different zipcode time paths (as we've been doing with the zipcode specific linear or quadratic trends) but it seems that it is a good thing to try to understand what is the variation that matters!

2020-10-09 18:22 UTC, diegogentilepassaro requested changes
@gabrieleborg, great job! 

I am through reviewing this issue. There are a few things to discuss so I will be active in case you respond!

2020-10-09 18:22 UTC, diegogentilepassaro commented on derived/zipcode_month/code/create_final_panels.do
> +	gsort zipcode year_month
I thought that the unbalanced panel was just keeping all data! Why do we need those lines?

2020-10-09 18:22 UTC, diegogentilepassaro commented on derived/zipcode_month/code/create_final_panels.do
> +	merge m:1 zipcode using `instub'/zip_ready.dta, nogen assert(1 2 3) keep(1 3)
Throughout this script we use a local and and if clause in main to state that we want to add demographics, but here we do it like this. I suggest that we always add them to all versions of the panel in the way we do here and that we ditch the complicated local if structure from everywhere as it would make the code much more readable.

2020-10-09 18:22 UTC, diegogentilepassaro commented on analysis/first_differences/code/first_differences.do
> +		}
Let's avoid the use of if and if else unless because it clutters the code a lot. For example, we could add an optional argument called name to the function, and add the name we want for each case through a string. Does that make sense?

2020-10-09 18:22 UTC, diegogentilepassaro commented on analysis/first_differences/code/first_differences.do
> +
I am not sure of what is this excerpt doing, could we please discuss?

2020-10-09 18:22 UTC, diegogentilepassaro commented on analysis/first_differences/code/first_differences.do
> +	distinct zipcode if e(sample)==1
Probably we don't need this line.

2020-10-09 18:28 UTC, gabrieleborg commented on derived/zipcode_month/code/create_final_panels.do
> +	gsort zipcode year_month
The idea here is that, yes, we are keeping all data but I am "dropping" the zipcodes with all missing. I say "dropping" because I am not actually dropping them unless they are missing for all rent series. This is because if, say, zip code x has all missing rent for sfcc we don't need it. But maybe it has obs for the 2br series. So I don't want to really drop it. What I do is I flag the unbalanced samples for the different rent series (sfcc, 2br, 5multi, etc), so that when we run the regression we just run it on the sample for that series (i.e. reghdfe blablablaal if sample_sfcc==1)

2020-10-09 18:32 UTC, gabrieleborg commented on derived/zipcode_month/code/create_final_panels.do
> +	merge m:1 zipcode using `instub'/zip_ready.dta, nogen assert(1 2 3) keep(1 3)
yeah I know that wasn't super nice. however I improved this part of the code in #54. There I simply create a function where you specify what you want to add (demo, econ controls etc), and it's much cleaner. You can have a look [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2350-controls-economic-shocks/derived/zipcode_month/code/create_final_panels.do) and, if you like it, you can just leave it like this so that when we merge #54 it will be improved.

2020-10-09 18:33 UTC, gabrieleborg commented on analysis/first_differences/code/first_differences.do
> +		}
Fine for me!

2020-10-09 18:38 UTC, gabrieleborg commented on analysis/first_differences/code/first_differences.do
> +
We probably don't need that, I think I missed it when I was ultimating the code. It basically center the plot by shifting t-1 to zero and adjusting all coefficients and SEs.

2020-10-09 18:53 UTC, diegogentilepassaro commented on derived/zipcode_month/code/create_final_panels.do
> +	gsort zipcode year_month
Thanks for clarifying @gabrieleborg! 

I still don't get why we need them. Those rows that have a missing sfcc but a populated 2br observation will only be used in the regression of the latter regardless of whether we do if sample_sfcc==1 purely based on what rows are populated. Right?

2020-10-09 18:55 UTC, diegogentilepassaro commented on derived/zipcode_month/code/create_final_panels.do
> +	merge m:1 zipcode using `instub'/zip_ready.dta, nogen assert(1 2 3) keep(1 3)
That is very neat @gabrieleborg! Let's make sure that we push that to master soon then. I can also take a look to that PR.

2020-10-09 18:56 UTC, diegogentilepassaro commented on analysis/first_differences/code/first_differences.do
> +		}
Your change looks good!

2020-10-09 18:59 UTC, gabrieleborg commented on derived/zipcode_month/code/create_final_panels.do
> +	gsort zipcode year_month
yeah in the regressions probably are redundant! but I think it's good to keep track of which zipcodes we are using with each series. So if for example we want to update some summary statistics for the unbalanced panel, we know exactly which zipcodes are we using, what's the rate of missings per zipcodes, etc? In any case we should double check that results don't change without the sample_sfcc==1

2020-10-09 19:15 UTC, diegogentilepassaro commented on derived/zipcode_month/code/create_final_panels.do
> +	gsort zipcode year_month
I see your point! Let's keep it then. One last question: do we drop some zipcode? Why would we have zipcodes without any data? If we don't drop any, then let's remove line `	drop if miss_sum==0
`

2020-10-09 19:15 UTC, diegogentilepassaro approved these changes

2020-10-09 19:20 UTC, gabrieleborg commented on derived/zipcode_month/code/create_final_panels.do
> +	gsort zipcode year_month
yeah actually the first reason it led me to write this piece of code was that the sample was incredibly large to begin with, really slowing down my Stata SE

2020-10-11 21:53 UTC, merged