PR for #58 composition bias
diegogentilepassaro/min_wage_rent pull request #61
Opened 2020-10-26 19:26 UTC by gabrieleborg

@diegogentilepassaro sending #58 to PR after having implemented the check you suggested. 

I have tested for the impact of changes in inventory in `analysis/first_differences_nlist`. As previously explained, we have both a [`preclean.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2358-composition-bias/analysis/first_differences_nlist/code/preclean.do) performing the usual cleaning of the dataset, and [`estimate_compbias.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2358-composition-bias/analysis/first_differences_nlist/code/estimate_compbias.do) that carries out the analysis.  

I have created the following table (need to add some description too)

<img width="665" alt="Screen Shot 2020-10-26 at 3 11 26 PM" src="https://user-images.githubusercontent.com/30894427/97217505-c35eb400-179d-11eb-8d6c-5fda753d8a9f.png">

- col1: our baseline model (depvar = D ln(medrent))
- col2: baseline + covar: D ln(n_listings)
- col3: placebo (depvar: D ln(n_listings))
- col4: placebo + covar: D ln(med listing price)

from the static persepctive, results don't look super nice. HOwever, when you look at the dynamic patterns, you can see that our baseline model does not really change, while the placebo one does not really detect any sudden jump at t = 0: 

**Baseline + covar**
<img width="924" alt="fd_model_nlistcontrol" src="https://user-images.githubusercontent.com/30894427/97217850-3d8f3880-179e-11eb-96cf-08a8be78cb73.png">

**Placebo & placebo + covar**
<img width="924" alt="fd_placebo_comparison" src="https://user-images.githubusercontent.com/30894427/97217987-6ca5aa00-179e-11eb-9aeb-a664f03e0205.png">

As for the weighting, I gave up for the moment as it sounds just very complicated even to understand. I am sending this to PR, feel free to experiment and let's agree on a final version of tables and plots!

2020-10-26 20:27 UTC, diegogentilepassaro requested changes

2020-10-26 20:27 UTC, diegogentilepassaro commented on analysis/first_differences_nlist/code/estimate_compbias.do
> +			mgroups("$\Delta y_{it}=\Delta$ ln(Median rent)" "$\Delta y_{it}=\Delta$ ln(No. listings)", pattern(1 0 1 0) ///
Let's remove the \Delta y_{it}= from the mgroups, as it is understood that it is the dependent variable.

2020-10-26 20:27 UTC, diegogentilepassaro commented on analysis/first_differences_nlist/code/estimate_compbias.do
> +	run_static_placebo, depvar(ln_med_rent_psqft_sfcc) placebovar(ln_n_listings_sfcc) covars(ln_med_list_psqft_sfcc) ///
Just taste: can we use controls instead of covars?

2020-10-26 20:27 UTC, diegogentilepassaro commented on analysis/first_differences_nlist/code/estimate_compbias.do
> +		vce(cluster `cluster') nocons
Main point here: It is a little weird to have this 4 models in the same table. I think we should show just the baseline and the analogous placebo (columns 1 and 3). Column 2 is weird to show here because it is a robustness and not a placebo that should live in the table that we control for a bunch of stuff. Column 4 is confusing, first because people will expect it to be the analogous of column 2 but for a different dependent variable and that is not what it is, and second, because we are only controlling for the list price (one particular control) without controlling for many things that also correlate with both that and the number of listing (economic shocks, building permits, etc). I think that we probably just ditch column 4 from the analysis.

2020-10-26 20:27 UTC, diegogentilepassaro commented on analysis/first_differences_nlist/code/estimate_compbias.do
> +		vce(cluster `cluster') nocons
I think that showing so much placebo is a little overkill, and the table is very clear. however, I am fine with keeping the dynamic placebo if you feel strongly about it but then, because of the reasons just stated in the comment above, let's ditch the version in which we control for the list price covariate.

2020-10-26 20:27 UTC, diegogentilepassaro requested changes
Great job @gabrieleborg! Let's see if we can kill this and have the draft out there at least for the professors soon :D

2020-10-26 20:38 UTC, gabrieleborg commented on analysis/first_differences_nlist/code/estimate_compbias.do
> +			mgroups("$\Delta y_{it}=\Delta$ ln(Median rent)" "$\Delta y_{it}=\Delta$ ln(No. listings)", pattern(1 0 1 0) ///
Agree

2020-10-26 20:44 UTC, gabrieleborg commented on analysis/first_differences_nlist/code/estimate_compbias.do
> +		vce(cluster `cluster') nocons
this makes sense. For the moment I will just update the table with having those 2 columns only. When you review it tomorrow, let's think then whether it makes sense to have such a small table, or whether we can show this results somewhere else.

2020-10-26 20:47 UTC, gabrieleborg commented on analysis/first_differences_nlist/code/estimate_compbias.do
> +		vce(cluster `cluster') nocons
I would maybe put that in the appendix? the reasoning here is that by only looking at the static table people may be mislead by the magnitude of the estimate, while if we also show the dynamics this helps in putting things back in perspective since it shows how many estimated leads and lags also have very large SEs and "jump around" a bit. what do you think?

2020-10-26 20:47 UTC, gabrieleborg commented on analysis/first_differences_nlist/code/estimate_compbias.do
> +		vce(cluster `cluster') nocons
agree in removing the plot with control.

2020-10-27 14:11 UTC, diegogentilepassaro commented on analysis/first_differences_nlist/code/estimate_compbias.do
> +		vce(cluster `cluster') nocons
Sounds good! Keeping the placebo with 2 columns is great. Let's remember considering adding to the robustness part a column controlling for the number of listings.

2020-10-27 14:11 UTC, diegogentilepassaro commented on analysis/first_differences_nlist/code/estimate_compbias.do
> +		vce(cluster `cluster') nocons
That sounds good @gabrieleborg! :D

2020-10-27 14:11 UTC, diegogentilepassaro approved these changes

2020-10-27 15:31 UTC, merged