PR for #40 het and salience
diegogentilepassaro/min_wage_rent pull request #62
Opened 2020-10-27 17:55 UTC by gabrieleborg

Sending #40 to PR. Please read the thread [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/40) to find description of what I have done so far (essentially, all heterogeneity results so far comes from [`analysis/first_differences/code/estimate_heterogeneity.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/analysis/first_differences/code/estimate_heterogeneity.do)

2020-10-28 14:07 UTC, santiagohermo commented
Task received @gabrieleborg. Thanks!

2020-10-29 21:23 UTC, diegogentilepassaro commented
@santiagohermo I will take over this PR! :D

2020-10-29 22:26 UTC, santiagohermo reviewed
I will leave this PR to @diegogentilepassaro then @gabrieleborg. I'll just leave the comment here I had made before the meeting, and mention to more things:

- As I said in the paper, I got the sense that we are compute too many tables which won't be used. I think it would be more efficient to just select the ones we want
- I made a few style changes in `make_lodes_ziplevel.R`

2020-10-30 21:06 UTC, diegogentilepassaro commented on lib/stata/min_wage/ado/event_plot_untreated_het.ado
> +program event_plot_untreated_het
I agree!

2020-10-30 21:22 UTC, diegogentilepassaro requested changes
Thanks for pushing this @gabrieleborg! I agree with @santiagohermo that we have many tables and figures that we don't use and that we won't probably use either. I propose to keep:
- Table 5 (in the current version of the draft)
- Figures with quartile-by-quartile estimates of the main 5/6 demographics (the ones in Table 5 plus a couple more at most). 
- Everything that outputs something using LODES data, so that we decide what to keep out of those in a follow-up task.

2020-10-30 21:22 UTC, diegogentilepassaro commented on base/demographics/code/tract_avgMW_13_18.R
> +main <- function() {
Not sure I understand what this new script does. Why do we need the MW average from 2013 to 2018 at the tract level?

2020-10-30 21:22 UTC, diegogentilepassaro commented on base/demographics/code/tract_avgMW_13_18.R
> +  #only problem now is that the base/demographic folder must run AFTER the base/zillow_min_wage, as it uses its output
Can't we make it part of base/zillow_min_wage? If it is based on min wage data, then it should live there.

2020-10-31 13:50 UTC, gabrieleborg commented on lib/stata/min_wage/ado/event_plot_untreated_het.ado
> +program event_plot_untreated_het
Agree! Done.

2020-10-31 13:59 UTC, gabrieleborg commented on base/demographics/code/tract_avgMW_13_18.R
> +main <- function() {
@diegogentilepassaro This was the first attempt at identifying MW workers using ACS and census data I tried. Basically, the logic was that I first compute, for each zipcode, the average MW in those years; then I take binned income data for each zipcode and assess, approximately, the share of workers earning less or equal that threshold for each zipcode. 

In the end we switched to LODES data for the draft. I think it's useful to recall the pros and cons of these two approaches, so that we can make an informed decision: 

_Census-based method_
    - PROs: census (ACS data really) provides a binned income distribution with finer categories, so in this sense it makes it easier to approximate the real share of MW workers
    - CONs: there's no information on the joint distribution income/age, which really helps finding MW workers as they mostly are low-income AND young

_LODES-based method_
    - PROs: it provides info on the share of low-income AND young (even though is only below 30 yrs old) workers for each zipcode
    - CONs: low-income can only be proxied by people earning less than $1250/month

2020-10-31 14:00 UTC, gabrieleborg commented on base/demographics/code/tract_avgMW_13_18.R
> +  #only problem now is that the base/demographic folder must run AFTER the base/zillow_min_wage, as it uses its output
If we end up keeping it, that could be a solution @diegogentilepassaro. Let me know what you think about my comment above, and then let's decide!

2020-10-31 15:26 UTC, gabrieleborg commented on base/demographics/code/tract_avgMW_13_18.R
> +main <- function() {
UPDATE: I re-run the heterogeneity analysis creating plots for the ACS-based MW worker variables but results are not that neat (you actually cannot spot any noticeable difference): 
<img width="924" alt="fd_static_heter_sh_mww_wmean2" src="https://user-images.githubusercontent.com/30894427/97782895-9bd76500-1b6a-11eb-8415-47e33c798698.png">
<img width="924" alt="fd_static_heter_sh_mww_renter_wmean2" src="https://user-images.githubusercontent.com/30894427/97782898-a265dc80-1b6a-11eb-8f03-c16ac328428a.png">

In the light of this, I think it's then better to identify MW workers with LODES data and discard this. I will wait to hear your feedback first though. One reason I think the results are that different is that I compute the ACS-based vars with a more complex procedure with many assumptions (see [`base/demographics/make_MWrenters_ziplevel.R`](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue40-Het-and-Salience/base/demographics/code/make_MWrenters_ziplevel.R)) that I believe ends up casting a "wider net": the measures are to broad to actually track MW workers?

2020-10-31 15:38 UTC, gabrieleborg commented
@diegogentilepassaro I implemented the changes requested. I ended up producing a few more het plot, but you can decide which one to keep!

2020-11-01 20:19 UTC, diegogentilepassaro commented on base/demographics/code/tract_avgMW_13_18.R
> +main <- function() {
@gabrieleborg, thanks for describing the pros and cons and for updating the heterogeneity analysis. A few comments/questions: 

1. Since the ACS is a very well-known dataset we still might want to keep it. We could try to fix the time dimension and instead of computing the average MW across some years, we could instead choose the initial year (2010) and compute the max MW in each zipcode for that year. Then compute the share of people falling below that income. 
2. As for this last computation of the share of people falling below some income level: the ACS has a variable called INCWAGE that comes at the annual level. We should divide it by the number of weeks that people works in a year, and the by the usual number of hours that people work in a week to obtain an hourly rate comparable with MW. Are we doing that? 
3. Are we using the proper ACS weights for the computation in 2.? 
2.  Are we sure that the ACS doesn't have age? That seems really weird!

2020-11-02 17:12 UTC, gabrieleborg commented on base/demographics/code/tract_avgMW_13_18.R
> +main <- function() {
@diegogentilepassaro here are some replies, I will work on those!

1. I can try that (if it's not too long). My only concern with that was that the bulk or our events is in the second part of the panel (2015-2019) and so I was fearing that using info from 2010 would return too imprecise measures (as opposed to using more recent data like we are doing now) !
2. RIght now we are doing the opposite, meaning bringing the minimum wage to an approximate annual total. This is because in the ACS we have data on the binned distribution of income, which I I thought it was more precise than using either an average or a median. The logic we are using is: compute, for each zipcode, the MW thresholds of annual earnings based on certain assumptions (e.g. number of MW workers in household, number of hours worked); and then get the share of residents that fall below those thresholds by looking at which bin of the income distribution is below the MW levels we find. That sounds as an alternative solution that we should definitely try, especially because what we are doing now is not very informative in the end!! the only thing is that I don't know whether I will have time to do it now, also considering that results with the LODES data are already more neat. 
3. I will double check that! 
4. We do have some actually, and I just checked that we cumputed some approximate share of MW workers based on BOTH age and income. I will review the analysis part once again to check where they end up.

2020-11-02 17:47 UTC, diegogentilepassaro commented on base/demographics/code/tract_avgMW_13_18.R
> +main <- function() {
Thanks for the replies @gabrieleborg! We can pause this and continue after #59 is sent to PR and then decide if we want to keep it. My replies:

1. Good point. Let's say we pick 2015 then.
2. We can check if the variables for number of weeks worked in a year and usual hours worked a week are nicely populated for 2015. If they do we should try!
3. 👍 
4. 👍

2020-11-26 14:34 UTC, santiagohermo commented
Any open issues here @gabrieleborg? Let me know if I should take a look at anything in particular so that we merge this back 👍

2020-11-26 14:39 UTC, gabrieleborg commented
Hey @santiagohermo ! mm not really, last time I implemented changes @diegogentilepassaro asked so I think we were good to merge. As I say in my last post, right now we are producing probably more plot than we'll use (we're producing a table with the main demo we want to discuss, but plots for more since it's easier to simply combine the selected ones in a figure) but I think it's good to have them for now so we can quickly decide what to show. 

I guess you can maybe re-run this updating the figure stile to make it ore similar to the main ones :) ! the only thing you have to be careful is starting from the right `derived` output because, as we discussed yesterday, the one produced in master does have an error in the demographic construction. I would suggest you update your drive with the latest dataset I produced in `derived_large` that I checked are correct!

2020-11-26 14:44 UTC, gabrieleborg commented
Actually there's one thing you could try @santiagohermo: I have recently updated the construction of ACS-based share of MW workers (to get a better benchmark estimate). The are variable, already in the latest `derived_large/baseline_rent_panel.dta` under the names: `sh_mww`, `sh_mww_ft`, and `sh_mww_pt`. you could try to run the heterogeneity analysis on them, because at the moment it didn't work on the older versions (see [this older post](https://github.com/diegogentilepassaro/min_wage_rent/pull/62#discussion_r515507906) here). At the moment the heterogeneity analysis works only with LODES-based MW workers definition, which is ok since we then are using that definition to build the experienced MW, but it would be interesting to see whether now we can get similar results with this new ACS-based measure of the share of MW workers living in a zipcode.

2020-11-28 13:04 UTC, santiagohermo commented
I was finally able to complete a run of `lodes/base` after updating this branch, @gabrieleborg. Changes (so that you are aware of them):

- I added a note in [LODES's readme](https://github.com/diegogentilepassaro/min_wage_rent/blob/2ef8feb6cebd39f276b7ec072ca842a8580dbd86/raw/lodes/readme.txt) about conflicting files for Alaska and South Dakota
- I moved data file manifest s to the repo (see [output folder](https://github.com/diegogentilepassaro/min_wage_rent/tree/2ef8feb6cebd39f276b7ec072ca842a8580dbd86/base/lodes/output)). Before they were being saved in the drive base_large
- I set the number of cores to 1 [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/2ef8feb6cebd39f276b7ec072ca842a8580dbd86/base/lodes/code/make_lodes_experienced_ziplevel.R#L15). It looks like parallelization with `mcapply` breaks in Windows if you use more than 1 core :(
- I updated LODES and demographics files in Google Drive.

I'm now building `derived/zipcode_month`. I'll later update those files in Google Drive and re-run the relevant analysis folders. Once I'm done I'll merge. Let me know if I'm missing anything!

2020-11-28 18:18 UTC, gabrieleborg commented
Thanks @santiagohermo ! 

That Is fine, but I am just realizing now that I think all the lodes-related part of the analysis should live in #65 (via master probably), since we decided to split the lodes-based part of the analysis (revolving around the construction of experienced MW) and the heterogeneity analysis, based on census data. This is also why yesterday I was struggling to find the lodes crosswalks in #65 I guess! In this sense, I think that we should remove the heterogeneity analysis based on lodes data from here (see [this line](https://github.com/diegogentilepassaro/min_wage_rent/blob/6edaf8e5cb387d26939c09f44b1a8651e3454aad/analysis/first_differences/code/heterogeneity.do#L15) in `analysis/first_differences/code/heterogeneity.do`) and produce those plots in `first_differences_expmw/code/figures.do`. This is what I was working on, in #65. What do you think?

2020-11-28 19:49 UTC, santiagohermo commented
I think that's a great plan @gabrieleborg! I'm merging here and you can update #65 and make the changes there

2020-11-28 19:49 UTC, merged