PR for #59 lodes based salience analysis
diegogentilepassaro/min_wage_rent pull request #68
Opened 2020-11-03 19:34 UTC by gabrieleborg

Sending this to PR @diegogentilepassaro. 

As per our meeting, I have updated the construction of the origin-destination zip-level matrix ([`base/lodes/code/make_odmatrix_ziplevel.R`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2359-LODES-based-salience-analysis/base/lodes/code/make_odmatrix_ziplevel.R)). As a first pass, I actually opted for keeping all destinations making up to 90 percent of the overall workforce of each origin zipcode (this is because while it's true that most zipcodes have more than 100 destinations, that sometimes was not true for smaller states). Minor problem here (let's see if you understand why @diegogentilepassaro 😜): I couldn't manage to run the whole folder via make.py as the R code throw an error related to how I specified a variable, that it says it does not find. To me it looks fine and when run directly...it works!!!!🤷🏽‍♂️

I then make. fresh re-run of `analysis/first_differences_expmw` while keeping only the main results, which are basically unchaged from those obtained with the "untrimmed" origin-destination matrix (left the functions computing the direct-indirect effect for the future, if we need them, just let me know if you think we can delete them!)

2020-11-05 22:37 UTC, diegogentilepassaro requested changes
@gabrieleborg I did a first pass of this PR. There are many questions so I will probably need to do a second pass once I understand your answers :D

2020-11-05 22:37 UTC, diegogentilepassaro commented on base/lodes/code/make_lodes_ziplevel.R
> +  dfzip <- dfzip[, lapply(.SD, function(x, w) sum(x*w, na.rm = T), w=tot_ratio),
How is tot_ratio defined exactly?

2020-11-05 22:37 UTC, diegogentilepassaro commented on base/lodes/code/make_lodes_ziplevel.R
> +    data[, st_tot := NULL]
I don't understand this part of code. What is exactly happening?

2020-11-05 22:37 UTC, diegogentilepassaro commented on base/lodes/code/make_odmatrix_ziplevel.R
> +  rm(xwalk_list)
I thought we converted the LODES data into zipcodes in the script before this one? Why do we need to do that twice? More broadly I am a little confused of the general idea of this script as I was expecting just the OD matrix construction happening here and not some zipcode tract transformations.

2020-11-05 22:37 UTC, diegogentilepassaro commented on base/lodes/code/make_odmatrix_ziplevel.R
> +  this_state_zip <- this_state_zip[totjob_cumsh<=.9, ][, c('h_totjob', 'totjob_cum', 'totjob_cumsh'):=NULL] #keep only destination zipcode that make up to 90 percent of total workforce
We should probably input the threshold as an argument of the program!

2020-11-06 14:35 UTC, gabrieleborg commented on analysis/first_differences_expmw/code/estimate_base.do
> +end
Agree. Let's keep it like this for now then, and let's change it only once after we merge this

2020-11-06 14:37 UTC, gabrieleborg commented on analysis/first_differences_expmw/code/preclean.do
> +end
In general, I think we should move all the preclean.do to derived because they're very similar for each specifcations. Shall we open an issue once we finish this?

2020-11-06 15:29 UTC, gabrieleborg commented on base/lodes/code/make_lodes_experienced_ziplevel.R
> +}
That was a great point @diegogentilepassaro ! I took some time to review how we use all xwalks throughout the analysis. 

In many scripts we use individual xwalks (e.g. `base/alt_rent`, or `base/demographic`), so I don't think there's scope for consolidation there. The main issue you are referring to I think is the construction of the a usps zipcode-month MW panel. Specifically: 

1. In order to assign each state, but mostly local and county MW to each usps zipcode we first clean zcta_place and zcta_county xwalk in `base/zillow_min_wage/cleanGeoRelationshipFiles.R`: here we create 3 files: zcta_place xwalk; zcta_county xwalk; and placename_placecode xwalk (this is because the local MW in the raw data are identified via locality name only, so we need this extra file to use the zcta_place xwalk)
2. These files are then used in `derived/AddMinWage.R`: we first use them to assign the correct MW to each zcta, and then we use a final zcta_zip xwalk to finally get a ziplevel panel of MW changes. 

What we do here in `base/lodes/make_lodes_experienced_ziplevel.R` is essentially the same we do in `derived/AddMinWage.R`, bceause we need the zipcode-month MW panel to compute the experienced measure. Only, we do it in `base`. 

A possible simplification I believe could be to create a separate script in `base` to independently build a usps zipcode-month MW panel, that we can then use to build both the experienced lodes, and our master dataset together with the Zillow data. 

I don't know whether this PR though is the right place to implement such large structural changes to the repo, but It's definitely good to remember all this if we wan to do it (prob we should). What do you think? I hope I was clear enough!

2020-11-06 15:34 UTC, gabrieleborg commented on base/lodes/code/make_lodes_ziplevel.R
> +  # Point of View (pov) : statistics for either residents ('rac') or workers ('wac') in given geographies
Here we don't use origin-destination logic, but we're only focusing, for each block, the characteristics of either the residents or the workers of that block. So: 
- for residents it means residents of a given block that they live in
- for workers it means workers of a given block to go to work in

2020-11-06 15:37 UTC, gabrieleborg commented on base/lodes/code/make_lodes_ziplevel.R
> +  dfzip <- dfzip[, lapply(.SD, function(x, w) sum(x*w, na.rm = T), w=tot_ratio),
This is a HUD crosswalk, you can find the definition [here](https://www.huduser.gov/portal/datasets/usps_crosswalk.html#codebook): 

_TOT_RATIO: The ratio of all addresses in the Tract, County, or CBSA-ZIP part to the total number of all types of addresses in the entire Tract, County, or CBSA._

2020-11-06 15:47 UTC, gabrieleborg commented on base/lodes/code/make_lodes_ziplevel.R
> +    data[, st_tot := NULL]
here I am computing state-level shares. Basically, before we simply compute, for each zipcode, the share of low-income workers, young workers, etc. These shares are computed for each zipcode individually, meaning out of the total number of workers in that given zipcode. But I think that was not super informative about the geographic distribution of MW workers: we may have 2 zipcodes where the share of lowincome workers is, say, 10 percent. But if the first zipcodes has 10 times the number of workers than the second one, that 10 percent means something entirely different than the 10 percent in the second zipcode. So, to better capture the geographical variation in where MW workers are, I compute for each zipcode, the share of lowincome, young, etc. workers that they have _out of the state total_. In this way in the previous example we will have that the first zipcode has a larger share of MW workers than the second one, that is very small. To do that I first compute the denominator at the state level, and then take the shares.

2020-11-06 15:53 UTC, gabrieleborg commented on base/lodes/code/make_odmatrix_ziplevel.R
> +  rm(xwalk_list)
the three scripts in the folder serves 2 different goals: 

- `make_lodes_ziplevel.R`: identify MW workers either based on where they live, or work. This computes the measures we used in the draft showing that the effect is larger where MW workers live, as opposed to where they work. But to do this exercise we don't need the od matrix: we can simply use the residence-based and worker-based lodes characteristics for each zipcode (derived from rac and wac files). 

- `make_odmatrix_ziplevel.R` and `make_lodes_experienced_ziplevel.R`: these files allows us to compute the Experienced MW measure, where we do need to know, for each zipcode, where do MW people go to work.

2020-11-06 15:55 UTC, gabrieleborg commented on base/lodes/code/make_odmatrix_ziplevel.R
> +  this_state_zip <- this_state_zip[totjob_cumsh<=.9, ][, c('h_totjob', 'totjob_cum', 'totjob_cumsh'):=NULL] #keep only destination zipcode that make up to 90 percent of total workforce
Agree! corrected

2020-11-09 00:48 UTC, santiagohermo commented on analysis/first_differences_expmw/code/preclean.do
> +end
This sounds like a good idea!

2020-11-09 20:13 UTC, diegogentilepassaro commented on analysis/first_differences_expmw/code/estimate_base.do
> +end
Sounds good :D

2020-11-09 20:13 UTC, diegogentilepassaro commented on analysis/first_differences_expmw/code/preclean.do
> +end
👍

2020-11-09 20:22 UTC, diegogentilepassaro commented on base/lodes/code/make_lodes_experienced_ziplevel.R
> +}
Thanks for this @gabrieleborg, your explanation is super clear! I agree with your plan! We will have to open issues for many housekeeping and redundancy changes soon after we have a draft. I agree that the change that you propose seems pretty substantial as it will affect many directories upstream but it seems not too complicated conceptually and it will be a great thing to have the match only in one place in case we need to revise it or change it. Also, it will make the creation of a replication much more easy to follow!

2020-11-09 20:25 UTC, diegogentilepassaro commented on base/lodes/code/make_lodes_ziplevel.R
> +  # Point of View (pov) : statistics for either residents ('rac') or workers ('wac') in given geographies
Thanks @gabrieleborg! I am happy I asked because that was not clear to me.

2020-11-09 20:28 UTC, diegogentilepassaro commented on base/lodes/code/make_lodes_ziplevel.R
> +  dfzip <- dfzip[, lapply(.SD, function(x, w) sum(x*w, na.rm = T), w=tot_ratio),
Thanks @gabrieleborg! So then we are using housing unit weights? I thought per [this comment](https://github.com/diegogentilepassaro/min_wage_rent/issues/59#issuecomment-720776880) that those were population ones. Maybe, we should create a little written tex where we explain the process that we do with LODES data in a paragraph?

2020-11-09 20:32 UTC, diegogentilepassaro commented on base/lodes/code/make_lodes_ziplevel.R
> +    data[, st_tot := NULL]
I am very happy I asked, because I was not expecting that. I believe that conceptually what should matter for the effect on rents on the zipcode is the share of people that have a MW within the zipcode (regardless of whether they work in that zipcode or in a neighboring one). I am not sure why the effect should be a function of the share of MW people of the state that live in a given zipcode. 

Could you please let me know how this affects the computation of the experienced MW at each zipcode? 

@santiagohermo tagging you in case you want to weigh your opinion here!

2020-11-09 20:40 UTC, diegogentilepassaro commented on base/lodes/code/make_odmatrix_ziplevel.R
> +  rm(xwalk_list)
Thanks for clarifying @gabrieleborg! Now I understand how things go. I thought that everything was a function of the OD matrix. i was expecting that computation to happen and then to use that both for computing the experienced MW and for computing the share of residents that get the MW on each zipcode (based on where they work and their characteristics). Probably, this is a good thing to discuss in our meeting so that we agree more generally 
:D

2020-11-09 20:41 UTC, diegogentilepassaro commented on base/lodes/code/make_lodes_ziplevel.R
> +make_xwalk <- function(instub) {
Sorry to bother again @gabrieleborg. Why do we need this xwalk?

2020-11-10 00:23 UTC, gabrieleborg commented on base/lodes/code/make_lodes_ziplevel.R
> +  dfzip <- dfzip[, lapply(.SD, function(x, w) sum(x*w, na.rm = T), w=tot_ratio),
My bad, my first answer was wrong! 
we are currently using all addresses, meaning both residential and business addresses. Ok, I will write a short paragraph soon :)

2020-11-10 01:36 UTC, gabrieleborg commented on base/lodes/code/make_lodes_ziplevel.R
> +    data[, st_tot := NULL]
Maybe in the next meeting we should reason a bit on the different implications of the two measures.! To answer your questions @diegogentilepassaro : 

- the choice of either zipcode- or state-level share does not affect the experienced MW at each zipcode (see my comment [here](https://github.com/diegogentilepassaro/min_wage_rent/pull/68#discussion_r518841415)!)
- Here are the heterogeneity plots with zipccode-level shares: 

<img width="924" alt="fd_static_heter_walall_29y_lowinc_zsh" src="https://user-images.githubusercontent.com/30894427/98616546-0145f700-22cb-11eb-9578-0f94475a0704.png">

<img width="924" alt="fd_static_heter_halall_29y_lowinc_zsh" src="https://user-images.githubusercontent.com/30894427/98616552-060aab00-22cb-11eb-8874-9953121021cd.png">

The plots are a bit more jumpy, but it looks like the conclusions that we can draw are similar: what matter the most is the share of MW residents, more than the share of MW workers in a zipcode.

2020-11-10 14:34 UTC, diegogentilepassaro commented on base/lodes/code/make_lodes_ziplevel.R
> +  dfzip <- dfzip[, lapply(.SD, function(x, w) sum(x*w, na.rm = T), w=tot_ratio),
That clarifies it @gabrieleborg! Thanks :D

2020-11-10 14:36 UTC, diegogentilepassaro commented on base/lodes/code/make_lodes_ziplevel.R
> +    data[, st_tot := NULL]
Thanks for the explanation @gabrieleborg! Now I understand how things go. Let's make sure we discuss this on our meeting :D

2020-11-10 14:38 UTC, diegogentilepassaro commented
@gabrieleborg I resolved most comments! I left open a couple that need your input and a couple that we should discuss in our meeting. 👍

2020-11-10 22:02 UTC, gabrieleborg commented on analysis/first_differences/output/data_file_manifest.log
> +  156600:149(94526):4115726683:608050444
@diegogentilepassaro when I run it from R yes, I do start from a clean environment. I literally open the file (`make_odmatrix_ziplevel.R`) and run it all. Here I post the error I get: 
<img width="578" alt="Screen Shot 2020-11-10 at 4 57 59 PM" src="https://user-images.githubusercontent.com/30894427/98738725-26dc0a80-2376-11eb-990a-0250e9b26246.png">
 
It basically does not recognize one of the argument of the function `make_odmatrix_state`, the input folder for the LODES data. It is very strange to me because that is simply a string with the location of the data, and again the strangest thing is that when I run it all from RStudio it works perfectly.

2020-11-12 03:14 UTC, santiagohermo commented on analysis/first_differences/output/data_file_manifest.log
> +  156600:149(94526):4115726683:608050444
Maybe if you remove the default options from the definition of the function (L52)?

2020-11-12 22:02 UTC, diegogentilepassaro commented on analysis/first_differences/output/data_file_manifest.log
> +  156600:149(94526):4115726683:608050444
I tried to pull the branch from github and run it and I got the following error:

![Screen Shot 2020-11-12 at 7 00 23 PM](https://user-images.githubusercontent.com/20582494/99001385-86bee680-2519-11eb-9dd4-9ab34540f9e6.png)

:/

2020-11-13 17:24 UTC, gabrieleborg commented on analysis/first_differences/output/data_file_manifest.log
> +  156600:149(94526):4115726683:608050444
@diegogentilepassaro  @santiagohermo I think I find out the solution: it was related to the way I wrote the last lapply() function. Basically I had to "wrap" the main function we are using in another one specifying explicitly all arguments. I suspect this is related to the different ways RStudio and batch R define the calling scope of function. See commit [69f47ae](https://github.com/diegogentilepassaro/min_wage_rent/pull/68/commits/69f47ae0bbd609a4fc38aca3b4bb7374a4adfdfe) to understand exactly what I did!

2020-11-13 17:33 UTC, diegogentilepassaro commented on analysis/first_differences/output/data_file_manifest.log
> +  156600:149(94526):4115726683:608050444
@gabrieleborg in `make_lodes_ziplevel.R' I still get the same mistake as before:

![Screen Shot 2020-11-13 at 2 32 14 PM](https://user-images.githubusercontent.com/20582494/99102704-36996000-25bd-11eb-8178-81a9df9e6dae.png)
 
:/

2020-11-13 22:54 UTC, diegogentilepassaro approved these changes
Just checked your logs and they look good! Green light to merge 👍

2020-11-14 00:13 UTC, merged